### ISSUE TITLE
Website with examples

### ISSUE THREAD

**Issue by domoritz** [uwdata/vsup#1]
It would be nice to have a live version of our examples.

**Comment by mcorrell** [comment]
I agree.
I think just the examples from the paper are fine:
Election
Flight Delays
Viral populations (w/ citation)

I also haven't done any due diligence on this repo yet; I just dumped in the working code from the paper, did a npm config, and pushed it out.

I think I won't be able to fire brain cells at this repo until April, but I should be up to review code/examples if by some miracle you get some spare time before then.

**Comment by mcorrell** [comment]
Thanks Dom!

**Comment by domoritz** [comment]
We still need to document how to use the library
