### ISSUE TITLE
How to pronounce VSUP?

### ISSUE THREAD

**Issue by na399** [uwdata/vsup#7]
Hi there,

Thanks for the brilliant work. I'm doing a presentation on my visualization using VSUP. 
I have a quick question. What is the preferred pronunciation of VSUP? 
V-S-U-P or V-Sup?

Cheers,
Max

**Comment by domoritz** [comment]
Great question. We say V-Sup.

**Comment by na399** [comment]
Thanks a lot. :D

**Comment by domoritz** [comment]
If you don't mind, @mcorrell and I would love if you could share your slides/presentation.
